# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:/VS/PhotoEditor/PhotoEditor/Photo Editor.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1417, 986)
        MainWindow.setMouseTracking(False)
        MainWindow.setStyleSheet("background-color: rgb(130, 130, 130);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1417, 34))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.menubar.setFont(font)
        self.menubar.setTabletTracking(True)
        self.menubar.setStyleSheet("background-color: rgb(74, 77, 80);\n"
"color: rgb(255, 250, 242);")
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        self.menu_4 = QtWidgets.QMenu(self.menubar)
        self.menu_4.setObjectName("menu_4")
        self.menu_3 = QtWidgets.QMenu(self.menu_4)
        self.menu_3.setObjectName("menu_3")
        self.menu_13 = QtWidgets.QMenu(self.menu_4)
        self.menu_13.setObjectName("menu_13")
        self.menu_5 = QtWidgets.QMenu(self.menubar)
        self.menu_5.setObjectName("menu_5")
        self.menu_14 = QtWidgets.QMenu(self.menu_5)
        self.menu_14.setObjectName("menu_14")
        self.menu_7 = QtWidgets.QMenu(self.menubar)
        self.menu_7.setObjectName("menu_7")
        self.menu_8 = QtWidgets.QMenu(self.menubar)
        self.menu_8.setObjectName("menu_8")
        self.menu_15 = QtWidgets.QMenu(self.menu_8)
        self.menu_15.setObjectName("menu_15")
        self.menu_9 = QtWidgets.QMenu(self.menubar)
        self.menu_9.setObjectName("menu_9")
        self.menu_10 = QtWidgets.QMenu(self.menubar)
        self.menu_10.setObjectName("menu_10")
        self.menu_11 = QtWidgets.QMenu(self.menubar)
        self.menu_11.setObjectName("menu_11")
        self.menu_12 = QtWidgets.QMenu(self.menubar)
        self.menu_12.setObjectName("menu_12")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setStyleSheet("background-color: rgb(74, 77, 80);\n"
"color: rgb(255, 250, 242);")
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setStyleSheet("background-color: rgb(74, 77, 80);\n"
"color: rgb(255, 250, 242);")
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.LeftToolBarArea, self.toolBar)
        self.action = QtWidgets.QAction(MainWindow)
        self.action.setObjectName("action")
        self.action_2 = QtWidgets.QAction(MainWindow)
        self.action_2.setObjectName("action_2")
        self.action_3 = QtWidgets.QAction(MainWindow)
        self.action_3.setObjectName("action_3")
        self.action_5 = QtWidgets.QAction(MainWindow)
        self.action_5.setObjectName("action_5")
        self.action_6 = QtWidgets.QAction(MainWindow)
        self.action_6.setObjectName("action_6")
        self.action_8 = QtWidgets.QAction(MainWindow)
        self.action_8.setObjectName("action_8")
        self.action_9 = QtWidgets.QAction(MainWindow)
        self.action_9.setObjectName("action_9")
        self.action_11 = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/undo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_11.setIcon(icon)
        self.action_11.setObjectName("action_11")
        self.action_12 = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icon/redo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_12.setIcon(icon1)
        self.action_12.setObjectName("action_12")
        self.action_14 = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icon/scissor.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_14.setIcon(icon2)
        self.action_14.setObjectName("action_14")
        self.action_15 = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icon/paste.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_15.setIcon(icon3)
        self.action_15.setObjectName("action_15")
        self.action_16 = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icon/copy.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_16.setIcon(icon4)
        self.action_16.setObjectName("action_16")
        self.actionwldnrl = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("img/eraser.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionwldnrl.setIcon(icon5)
        self.actionwldnrl.setObjectName("actionwldnrl")
        self.action_18 = QtWidgets.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icon/search.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_18.setIcon(icon6)
        self.action_18.setObjectName("action_18")
        self.action_22 = QtWidgets.QAction(MainWindow)
        self.action_22.setObjectName("action_22")
        self.action_23 = QtWidgets.QAction(MainWindow)
        self.action_23.setObjectName("action_23")
        self.action_24 = QtWidgets.QAction(MainWindow)
        self.action_24.setObjectName("action_24")
        self.action_25 = QtWidgets.QAction(MainWindow)
        self.action_25.setObjectName("action_25")
        self.action_26 = QtWidgets.QAction(MainWindow)
        self.action_26.setObjectName("action_26")
        self.action_28 = QtWidgets.QAction(MainWindow)
        self.action_28.setObjectName("action_28")
        self.action_29 = QtWidgets.QAction(MainWindow)
        self.action_29.setObjectName("action_29")
        self.action_29.setShortcut("Alt+F4")
        self.action_30 = QtWidgets.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icon/crop.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_30.setIcon(icon7)
        self.action_30.setObjectName("action_30")
        self.action_32 = QtWidgets.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icon/enlarge.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_32.setIcon(icon8)
        self.action_32.setObjectName("action_32")
        self.action_33 = QtWidgets.QAction(MainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/icon/reduction.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_33.setIcon(icon9)
        self.action_33.setObjectName("action_33")
        self.action_34 = QtWidgets.QAction(MainWindow)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/icon/paint bucket.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_34.setIcon(icon10)
        self.action_34.setObjectName("action_34")
        self.action_35 = QtWidgets.QAction(MainWindow)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/icon/brush.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_35.setIcon(icon11)
        self.action_35.setObjectName("action_35")
        self.action_36 = QtWidgets.QAction(MainWindow)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/icon/text.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_36.setIcon(icon12)
        self.action_36.setObjectName("action_36")
        self.action_38 = QtWidgets.QAction(MainWindow)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/icon/rectangular marquee.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_38.setIcon(icon13)
        self.action_38.setObjectName("action_38")
        self.action_39 = QtWidgets.QAction(MainWindow)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/icon/lasso.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_39.setIcon(icon14)
        self.action_39.setObjectName("action_39")
        self.action_40 = QtWidgets.QAction(MainWindow)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(":/icon/move tool.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_40.setIcon(icon15)
        self.action_40.setObjectName("action_40")
        self.action_43 = QtWidgets.QAction(MainWindow)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(":/icon/stamp.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_43.setIcon(icon16)
        self.action_43.setObjectName("action_43")
        self.action_44 = QtWidgets.QAction(MainWindow)
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(":/icon/rub.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_44.setIcon(icon17)
        self.action_44.setObjectName("action_44")
        self.action_45 = QtWidgets.QAction(MainWindow)
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap(":/icon/spoid.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_45.setIcon(icon18)
        self.action_45.setObjectName("action_45")
        self.action_46 = QtWidgets.QAction(MainWindow)
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap(":/icon/purge.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_46.setIcon(icon19)
        self.action_46.setObjectName("action_46")
        self.action_48 = QtWidgets.QAction(MainWindow)
        self.action_48.setObjectName("action_48")
        self.action_49 = QtWidgets.QAction(MainWindow)
        self.action_49.setObjectName("action_49")
        self.action_51 = QtWidgets.QAction(MainWindow)
        self.action_51.setObjectName("action_51")
        self.action_52 = QtWidgets.QAction(MainWindow)
        self.action_52.setObjectName("action_52")
        self.actionRGB = QtWidgets.QAction(MainWindow)
        self.actionRGB.setObjectName("actionRGB")
        self.action_53 = QtWidgets.QAction(MainWindow)
        self.action_53.setObjectName("action_53")
        self.action_54 = QtWidgets.QAction(MainWindow)
        self.action_54.setObjectName("action_54")
        self.action_55 = QtWidgets.QAction(MainWindow)
        self.action_55.setObjectName("action_55")
        self.action_56 = QtWidgets.QAction(MainWindow)
        self.action_56.setObjectName("action_56")
        self.action_57 = QtWidgets.QAction(MainWindow)
        self.action_57.setObjectName("action_57")
        self.action_60 = QtWidgets.QAction(MainWindow)
        self.action_60.setObjectName("action_60")
        self.action90 = QtWidgets.QAction(MainWindow)
        self.action90.setObjectName("action90")
        self.action_61 = QtWidgets.QAction(MainWindow)
        self.action_61.setObjectName("action_61")
        self.action_63 = QtWidgets.QAction(MainWindow)
        self.action_63.setObjectName("action_63")
        self.action_64 = QtWidgets.QAction(MainWindow)
        self.action_64.setObjectName("action_64")
        self.action_66 = QtWidgets.QAction(MainWindow)
        self.action_66.setObjectName("action_66")
        self.action_67 = QtWidgets.QAction(MainWindow)
        self.action_67.setObjectName("action_67")
        self.action_68 = QtWidgets.QAction(MainWindow)
        self.action_68.setObjectName("action_68")
        self.action_69 = QtWidgets.QAction(MainWindow)
        self.action_69.setObjectName("action_69")
        self.action_70 = QtWidgets.QAction(MainWindow)
        self.action_70.setObjectName("action_70")
        self.action_71 = QtWidgets.QAction(MainWindow)
        self.action_71.setObjectName("action_71")
        self.action_72 = QtWidgets.QAction(MainWindow)
        self.action_72.setObjectName("action_72")
        self.menu.addAction(self.action)
        self.menu.addAction(self.action_2)
        self.menu.addAction(self.action_3)
        self.menu.addSeparator()
        self.menu.addAction(self.action_5)
        self.menu.addAction(self.action_6)
        self.menu.addSeparator()
        self.menu.addAction(self.action_8)
        self.menu.addAction(self.action_9)
        self.menu.addSeparator()
        self.menu.addAction(self.action_72)
        self.menu.addSeparator()
        self.menu.addAction(self.action_29)
        self.menu_2.addAction(self.action_11)
        self.menu_2.addAction(self.action_12)
        self.menu_2.addSeparator()
        self.menu_2.addAction(self.action_16)
        self.menu_2.addAction(self.action_14)
        self.menu_2.addAction(self.action_15)
        self.menu_2.addSeparator()
        self.menu_2.addAction(self.action_18)
        self.menu_3.addAction(self.action_22)
        self.menu_3.addAction(self.action_23)
        self.menu_3.addAction(self.action_24)
        self.menu_3.addAction(self.action_25)
        self.menu_3.addAction(self.action_26)
        self.menu_3.addSeparator()
        self.menu_3.addAction(self.action_28)
        self.menu_13.addAction(self.actionRGB)
        self.menu_13.addAction(self.action_53)
        self.menu_13.addAction(self.action_54)
        self.menu_4.addAction(self.menu_13.menuAction())
        self.menu_4.addSeparator()
        self.menu_4.addAction(self.menu_3.menuAction())
        self.menu_4.addSeparator()
        self.menu_4.addAction(self.action_30)
        self.menu_14.addAction(self.action_60)
        self.menu_14.addAction(self.action_61)
        self.menu_14.addAction(self.action90)
        self.menu_5.addAction(self.action_55)
        self.menu_5.addAction(self.action_56)
        self.menu_5.addAction(self.action_57)
        self.menu_5.addSeparator()
        self.menu_5.addAction(self.menu_14.menuAction())
        self.menu_5.addSeparator()
        self.menu_5.addAction(self.action_63)
        self.menu_5.addAction(self.action_64)
        self.menu_7.addAction(self.action_69)
        self.menu_7.addAction(self.action_70)
        self.menu_15.addAction(self.action_66)
        self.menu_15.addAction(self.action_71)
        self.menu_8.addAction(self.menu_15.menuAction())
        self.menu_9.addAction(self.action_32)
        self.menu_9.addAction(self.action_33)
        self.menu_9.addSeparator()
        self.menu_9.addAction(self.action_67)
        self.menu_9.addAction(self.action_68)
        self.menu_10.addAction(self.action_49)
        self.menu_10.addSeparator()
        self.menu_10.addAction(self.action_51)
        self.menu_10.addAction(self.action_52)
        self.menu_11.addAction(self.action_48)
        self.menu_12.addAction(self.action_40)
        self.menu_12.addSeparator()
        self.menu_12.addAction(self.action_38)
        self.menu_12.addAction(self.action_39)
        self.menu_12.addAction(self.action_46)
        self.menu_12.addSeparator()
        self.menu_12.addAction(self.action_35)
        self.menu_12.addAction(self.actionwldnrl)
        self.menu_12.addAction(self.action_34)
        self.menu_12.addSeparator()
        self.menu_12.addAction(self.action_43)
        self.menu_12.addAction(self.action_44)
        self.menu_12.addAction(self.action_45)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menu_4.menuAction())
        self.menubar.addAction(self.menu_5.menuAction())
        self.menubar.addAction(self.menu_7.menuAction())
        self.menubar.addAction(self.menu_12.menuAction())
        self.menubar.addAction(self.menu_8.menuAction())
        self.menubar.addAction(self.menu_9.menuAction())
        self.menubar.addAction(self.menu_10.menuAction())
        self.menubar.addAction(self.menu_11.menuAction())
        self.toolBar.addAction(self.action_40)
        self.toolBar.addAction(self.action_38)
        self.toolBar.addAction(self.action_39)
        self.toolBar.addAction(self.action_46)
        self.toolBar.addAction(self.action_30)
        self.toolBar.addAction(self.action_34)
        self.toolBar.addAction(self.action_35)
        self.toolBar.addAction(self.actionwldnrl)
        self.toolBar.addAction(self.action_43)
        self.toolBar.addAction(self.action_44)
        self.toolBar.addAction(self.action_45)
        self.toolBar.addAction(self.action_36)
        self.toolBar.addAction(self.action_32)
        self.toolBar.addAction(self.action_33)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Photo Editor"))
        self.menu.setTitle(_translate("MainWindow", "파일"))
        self.menu_2.setTitle(_translate("MainWindow", "편집"))
        self.menu_4.setTitle(_translate("MainWindow", "이미지"))
        self.menu_3.setTitle(_translate("MainWindow", "색상 조정"))
        self.menu_13.setTitle(_translate("MainWindow", "모드"))
        self.menu_5.setTitle(_translate("MainWindow", "레이어"))
        self.menu_14.setTitle(_translate("MainWindow", "변형"))
        self.menu_7.setTitle(_translate("MainWindow", "선택"))
        self.menu_8.setTitle(_translate("MainWindow", "필터"))
        self.menu_15.setTitle(_translate("MainWindow", "흐림 처리"))
        self.menu_9.setTitle(_translate("MainWindow", "보기"))
        self.menu_10.setTitle(_translate("MainWindow", "창"))
        self.menu_11.setTitle(_translate("MainWindow", "도움말"))
        self.menu_12.setTitle(_translate("MainWindow", "도구"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.action.setText(_translate("MainWindow", "불러오기"))
        self.action_2.setText(_translate("MainWindow", "최근 파일"))
        self.action_3.setText(_translate("MainWindow", "새로 만들기"))
        self.action_5.setText(_translate("MainWindow", "저장"))
        self.action_6.setText(_translate("MainWindow", "다른 이름으로 저장"))
        self.action_8.setText(_translate("MainWindow", "들여오기"))
        self.action_9.setText(_translate("MainWindow", "내보내기"))
        self.action_11.setText(_translate("MainWindow", "실행 취소"))
        self.action_12.setText(_translate("MainWindow", "다시 실행"))
        self.action_14.setText(_translate("MainWindow", "잘라내기"))
        self.action_15.setText(_translate("MainWindow", "붙여넣기"))
        self.action_16.setText(_translate("MainWindow", "복사"))
        self.actionwldnrl.setText(_translate("MainWindow", "지우기"))
        self.action_18.setText(_translate("MainWindow", "텍스트 찾기"))
        self.action_22.setText(_translate("MainWindow", "명도/대비"))
        self.action_23.setText(_translate("MainWindow", "레벨"))
        self.action_24.setText(_translate("MainWindow", "곡선"))
        self.action_25.setText(_translate("MainWindow", "노출"))
        self.action_26.setText(_translate("MainWindow", "활기"))
        self.action_28.setText(_translate("MainWindow", "균일화"))
        self.action_29.setText(_translate("MainWindow", "종료"))
        self.action_30.setText(_translate("MainWindow", "자르기"))
        self.action_32.setText(_translate("MainWindow", "확대"))
        self.action_33.setText(_translate("MainWindow", "축소"))
        self.action_34.setText(_translate("MainWindow", "색 채우기"))
        self.action_35.setText(_translate("MainWindow", "브러시"))
        self.action_36.setText(_translate("MainWindow", "텍스트 도구"))
        self.action_38.setText(_translate("MainWindow", "사각형 선택 영역 도구"))
        self.action_39.setText(_translate("MainWindow", "자유 선택 도구"))
        self.action_40.setText(_translate("MainWindow", "이동 도구"))
        self.action_43.setText(_translate("MainWindow", "도장 도구"))
        self.action_44.setText(_translate("MainWindow", "문지르기 도구"))
        self.action_45.setText(_translate("MainWindow", "색상 추출 도구"))
        self.action_46.setText(_translate("MainWindow", "퍼지 영역 도구"))
        self.action_48.setText(_translate("MainWindow", "도움말"))
        self.action_49.setText(_translate("MainWindow", "최근 닫은 탭"))
        self.action_51.setText(_translate("MainWindow", "탭 숨기기"))
        self.action_52.setText(_translate("MainWindow", "탭 보이기"))
        self.actionRGB.setText(_translate("MainWindow", "RGB"))
        self.action_53.setText(_translate("MainWindow", "그레이스케일"))
        self.action_54.setText(_translate("MainWindow", "인덱스"))
        self.action_55.setText(_translate("MainWindow", "새 레이어"))
        self.action_56.setText(_translate("MainWindow", "레이어 복제"))
        self.action_57.setText(_translate("MainWindow", "레이어 삭제"))
        self.action_60.setText(_translate("MainWindow", "좌우 뒤집기"))
        self.action90.setText(_translate("MainWindow", "90º 뒤집기"))
        self.action_61.setText(_translate("MainWindow", "상하 뒤집기"))
        self.action_63.setText(_translate("MainWindow", "레이어 앞으로 보내기"))
        self.action_64.setText(_translate("MainWindow", "레이어 뒤로 보내기"))
        self.action_66.setText(_translate("MainWindow", "가우시안 필터"))
        self.action_67.setText(_translate("MainWindow", "창 크기를 이미지에 맞춤"))
        self.action_68.setText(_translate("MainWindow", "전체화면"))
        self.action_69.setText(_translate("MainWindow", "모두 선택"))
        self.action_70.setText(_translate("MainWindow", "반전"))
        self.action_71.setText(_translate("MainWindow", "중간값 필터"))
        self.action_72.setText(_translate("MainWindow", "설정"))

import images_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

